- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Configure unattended-upgrades
  template:
    src: unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
