- name: Configure users
  user:
    name: "{{ item }}"
    append: yes ## Don't set these as our *only* groups!
    groups: adm,sudo
    shell: /bin/bash
  with_items:
    - werner

- name: Configure SSH keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  with_items:
    - name: werner
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ/S7dOGoEj/S9HGgdtTiQLfifE+RgVMxMkw0roHW+90 jan

- name: Ensure passwordless sudo
  lineinfile:
    line: "%sudo	ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers
    regexp: "^%sudo	ALL=\\(ALL:ALL\\).*"
